# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: 'Project1_CigarShop'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(solutionPath) --logger trx --collect "Code coverage"
    /p:CollectCoverage=true 
    /p:CoverletOutputFormat=opencover 
    /p:Exclude="[xunit*]*"
  displayName: 'dotnet build $(buildConfiguration) $(solutionPath)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: SonarCloudAnalyze@1
  inputs: {}

extraProperties:
sonar.cs.opencover.reportsPath="$(Build.ArtifactStagingDirectory)/coverage/*":
