# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: 'Project1_CigarShop'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'tllewellProject1'
    organization: 'tllewell-github'
    scannerMode: 'MSBuild'
    projectKey: 'TLewellProject1'
    projectName: 'Project1_CigarShop'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"

 

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(solutionPath)
  displayName: 'dotnet build $(buildConfiguration)'


- script: dotnet test
    --configuration $(buildConfiguration)
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput='$(Build.ArtifactStagingDirectory)/coverage/'
    /p:Exclude="[xunit*]*"
  workingDirectory: $(solutionPath)
  displayName: 'dotnet test $(buildConfiguration)'

- task: SonarCloudAnalyze@1
  inputs: {}

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '60'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial (9a605f76-7edb-4db7-b774-cb256b2d8b9a)'
    appType: 'webApp'
    WebAppName: '1904-llewellyn-cigars'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
